# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbff96d2f0a1ec8942c0cc2e22f275157db7bc20922d5d97aa8d99f1750e8af7541b27a5c791eda74a1441556c1642c10d712acfb2301cb4bfcaa7d7815f6de4

test:
  secret_key_base: 1319877346d7ef716041d0441e74d32a5a2353cd1ddf8cb00e8fdfbcafff594d92d0fac9d2da6989fa6c433f35ca5f543ba644e5c05c82d63c72154f43c8e7ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
